on: [push, pull_request]

jobs:
  run-app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: 11

      - name: Building my app
        run: |
          mvn clean package -DskipTests

      - name: Run App
        run: |
          java -jar ./target/gitactiontest-0.0.1-SNAPSHOT.jar
          sleep 60s

  run-newman:
    runs-on: ubuntu-latest
    needs: [run-app]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Newman tests
        uses: matt-ball/newman-action@master
        with:
          collection: my-test.json
          environment: api-env.json

      - name: Check conditions and re-run if needed
        run: |
          # Check conditions here
          # If conditions are met, re-run the workflow
          if [[ CONDITIONS_MET ]]; then
            echo "Conditions met, re-running the workflow..."
            exit 1 # This will trigger a rerun of the workflow
          else
            echo "Conditions not met, proceeding with the workflow..."
          fi
