name: API_TEST
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 1.21
        uses: actions/setup-java@v1
        with:
          java-version: 1.21

      - name: Building my app
        run: |
          mvn clean package -DskipTests

      - name: Running my App
        id: run-app
        run: |
          java -jar ./target/gitactiontest-0.0.1-SNAPSHOT.jar
          sleep 40

  newman-action:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Newman action
        run: |
          # Adjust the command as needed
          echo "Running Newman"
          npm install -g newman
          newman run my-test.json
