name: Scheduled Workflow

on:
  schedule:
    - cron: '0 0 * * *'  # Run every day at midnight

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: 11

      - name: Building my app
        run: |
          mvn clean package -DskipTests

      - name: Run Newman tests
        uses: matt-ball/newman-action@master
        with:
          collection: my-test.json
          environment: api-env.json
