on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: 11

      - name: Building my app
        run: |
          mvn clean package -DskipTests

      - name: Running my App
        id: run-app
        run: |
          java -jar ./target/gitactiontest-0.0.1-SNAPSHOT.jar
          sleep 60s

      - name: newman action
        continue-on-error: true
        uses: matt-ball/newman-action@master
        with:
          collection: my-test.json
          environment: api-env.json

      - name: Running my App next newman not running
        run: echo "This step runs after the build job"
