name: Build and Test Spring Boot App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '21'

      - name: Build with Maven
        run: |
          ./mvnw clean install -DskipTests=true

  test:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Start Postman Service
        run: docker run -d --name postman-service -p 3000:3000 postman/newman_ubuntu1404

      - name: Run Postman Collection
        run: |
          docker exec postman-service newman run ./my-test.json

      - name: Stop Postman Service
        run: docker stop postman-service
