name: relase tag
on:
  push:
    branches: [release]

jobs:
  release-on-push:
    runs-on: ubuntu-latest
  steps:
    name: Create Github Relase
    id: create-new-relase
    env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    with:
        tag_name: ${{github.run_number}}
        release-name: Release ${{github.run_number}}
      