name: project cicd flow

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: '21'
          distribution: 'adopt'
          cache: maven
      - name: Build with Maven
        run: mvn clean install

      - name: Build & push Docker image
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: vk786/test-app-my
          tags: latest
          registry: docker.io
          dockerfile: Dockerfile
          username: ${{ secrets.USER_NAME }}
          password: ${{ secrets.USER_PASSWORD }}
      - name: Run docker container
        run: docker run -d -p 8080:8080 vk786/test-app-my:latest
      - name: wait for docker container to start
        run: sleep 20
      - name: install newman
        run:  npm install -g newman
      - name: set env test
        run:
        with:
          environment: api-env.json
      - name: run postman collection
        run: newman run my-test.json
